services:
  - type: web
    name: site-data-due-diligence
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python site_data_app_nice_gui.py
    envVars:
      - key: ENV
        value: prod
      - key: NICEGUI_SECRET_KEY
        generateValue: true
